### ISSUE TITLE
Workflow fails if {var:devices} is not empty

### ISSUE THREAD

**Issue by joshuawagner** [stroebjo/alfred-pushover#1]
Here is what I have in my variables pane:
![image](https://user-images.githubusercontent.com/1421213/119293938-03452700-bc19-11eb-83d1-e41ccb365e6b.png)

And here is my log:
![image](https://user-images.githubusercontent.com/1421213/119293965-10621600-bc19-11eb-8580-9f83290daadb.png)

The workflow works properly without the devices variable specified. And Pushover is working for me from Keyboard Maestro as well. Any ideas on this?

**Comment by stroebjo** [comment]
The log seems alright so far (same for me, also with 2 devices). But can you check if the log is longer? It should have some more lines.

I noticed that Alfred has a new Condition-Block for the Workflow logic, I updated to it and pushed a new release. But I don't think this could fix your issue, but maybe it's worth a try. 

And just to make sure, the `APP_TOKEN` and `USER_KEY` variables are set, and without the `devices` variable you can send the message to all your Pushover devices?

**Comment by joshuawagner** [comment]
Thanks for the updated logic. Correct that it didn't solve the problem.
That was the full log and here it is again with the updated workflow. The first run with 'test' goes through fine with no devices specified in the variables pane. Next, when I put the variable in as before, it never finishes.
![image](https://user-images.githubusercontent.com/1421213/119390254-4c01ec00-bcbc-11eb-83bf-c496ee7d4464.png)

**Comment by stroebjo** [comment]
This sounds like the device selection runs in to some sort of loop. I cleaned up the code a bit, maybe this fixes it. There was some strange, old code, though I have no idea how this could trigger this behaviour. Please try the attached `Pushover-dev1` version. 

If this doesn't work, I added a `Pushover-dev2` as well, this will print the PHP version on your system as well as the set device variable. This should at least produce an `ERROR` in the log from which we can hopefully narrow down this issue.

Also on what what macOS/Alfred version are you?

I had to zip the workflows, so GitHub would allow me to attach dem: [workflows.zip](https://github.com/stroebjo/alfred-pushover/files/6534564/workflows.zip)

**Comment by stroebjo** [comment]
I've rewritten the workflow in Python, for macOS Monterey. If this is still relevant in the new version, please open a new issue.
