### ISSUE TITLE
can't use pushc with picture in clipboard

### ISSUE THREAD

**Issue by lilarcor** [stroebjo/alfred-pushover#2]
Hello, 
I got following error if I use pushover clipboard to send a picture. Please have a look.
Reason: Couldn't posix_spawn: error 7

/bin/bash

Check that the selected language exists on your system.

If you're syncing Alfred's preferences, also check that all related workflow files exist locally.

**Comment by stroebjo** [comment]
Hi, are you on macOS 12 Monterey? This workflow depends on PHP, which is no longer bundled with macOS 12, I suppose that's the issue (see https://www.alfredapp.com/blog/releases/alfred-4-6-ready-for-macos-monterey/). 

I will update the workflow in the next few months but I'm not sure when…

**Comment by lilarcor** [comment]
Hello, Sir,
I am using MacOS 11.6. Looking forward to new version.

**Comment by stroebjo** [comment]
I've rewritten the workflow in Python, for macOS Monterey now. See the latest release.

In case for the image preview to work you need to install the 3rd party requests library as noted in the README. Please check and reopen the issue in case it still gives you problems.
